    name: Hamouchene Classroom Workflow

    on: 
      push:
        branches:
        - '*'
        
    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

          # start tests
            - name: Run autograding tests
              uses: education/autograding@v1
              id: autograder
              continue-on-error: false
